name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./build.sh
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: BugBlock.xcframework
          path: build
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/BugBlock.xcframework"
          token: ${{ secrets.GITHUB_TOKEN }}
